# Generated by Django 5.1.6 on 2025-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('client_id', models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='Client ID Авито')),
                ('client_secret', models.CharField(blank=True, default='none', max_length=100, null=True, verbose_name='Client Secret Авито')),
                ('day_expenses', models.FloatField(default=0, max_length=40, verbose_name='дневные рассходы')),
                ('weakly_expenses', models.CharField(default=0, max_length=50, verbose_name='недельнве расходы')),
                ('daily_report_tg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID для дневных отчетов')),
                ('weekly_report_tg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID для недельных отчетов')),
                ('last_balance', models.FloatField(default=0, verbose_name='Последний известный баланс')),
            ],
        ),
    ]
