# Generated by Django 5.1.6 on 2025-04-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_chats',
            field=models.IntegerField(default=0, verbose_name='количество чатов за день'),
        ),
        migrations.AddField(
            model_name='user',
            name='week_chats',
            field=models.IntegerField(default=0, verbose_name='количество чатов за неделю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='day_expenses',
            field=models.FloatField(default=0, verbose_name='дневные расходы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weakly_expenses',
            field=models.FloatField(default=0, verbose_name='недельные расходы'),
        ),
    ]
