# Generated by Django 5.1.6 on 2025-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avito_api_key',
        ),
        migrations.AddField(
            model_name='user',
            name='client_secret',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, verbose_name='Client Secret Авито'),
        ),
    ]
