# Generated by Django 5.1.6 on 2025-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avito_client_id',
            field=models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='client_id Авито'),
        ),
        migrations.AddField(
            model_name='user',
            name='avito_client_secret',
            field=models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='client_secret Авито'),
        ),
    ]
