# Generated by Django 5.1.6 on 2025-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_change_avito_api_key_to_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='Client ID Авито'),
        ),
    ]
