# Generated by Django 5.1.6 on 2025-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_avito_client_id_user_avito_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avito_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='токен Авито'),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_stats',
            field=models.TextField(blank=True, null=True, verbose_name='Статистика за предыдущий день'),
        ),
    ]
