# Generated by Django 5.1.6 on 2025-04-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_day_chats_user_week_chats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_expenses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weakly_expenses',
        ),
    ]
