# Generated by Django 5.1.6 on 2025-04-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_user_day_expenses_remove_user_last_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_chats',
        ),
        migrations.RemoveField(
            model_name='user',
            name='week_chats',
        ),
    ]
