# Generated by Django 5.1.6 on 2025-04-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_avito_token_user_previous_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='previous_stats',
        ),
    ]
