# Generated by Django 5.1.6 on 2025-05-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_daily_expense_user_last_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя аккаунта')),
                ('client_id', models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='Client ID Авито')),
                ('client_secret', models.CharField(blank=True, default='none', max_length=100, null=True, verbose_name='Client Secret Авито')),
                ('daily_report_tg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID для дневных отчетов')),
                ('weekly_report_tg_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID для недельных отчетов')),
                ('daily_expense', models.FloatField(default=0, verbose_name='Дневной расход')),
                ('weekly_expense', models.FloatField(default=0, verbose_name='Недельный расход')),
                ('last_balance', models.FloatField(default=0, verbose_name='Последний баланс')),
                ('last_balance_check', models.DateTimeField(blank=True, null=True, verbose_name='Время последней проверки баланса')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_expense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_report_tg_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_balance_check',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_expense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_report_tg_id',
        ),
        migrations.CreateModel(
            name='UserAvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.avitoaccount', verbose_name='Аккаунт Авито')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_accounts', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь пользователь-аккаунт',
                'verbose_name_plural': 'Связи пользователей и аккаунтов',
                'unique_together': {('user', 'avito_account')},
            },
        ),
    ]
