# Generated by Django 5.1.6 on 2025-05-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_avitoaccount_remove_user_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avitoaccount',
            options={'verbose_name': 'Аккаунт Авито', 'verbose_name_plural': 'Аккаунты Авито'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отчета')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего объявлений')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('contacts', models.IntegerField(default=0, verbose_name='Контакты')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Конверсия в контакты (%)')),
                ('contact_cost', models.FloatField(default=0, verbose_name='Стоимость контакта')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Всего звонков')),
                ('answered_calls', models.IntegerField(default=0, verbose_name='Отвеченные звонки')),
                ('missed_calls', models.IntegerField(default=0, verbose_name='Пропущенные звонки')),
                ('total_chats', models.IntegerField(default=0, verbose_name='Всего чатов')),
                ('new_chats', models.IntegerField(default=0, verbose_name='Новые чаты')),
                ('unanswered_chats', models.IntegerField(default=0, verbose_name='Неотвеченные чаты')),
                ('phones_received', models.IntegerField(default=0, verbose_name='Показы телефона')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Всего отзывов')),
                ('new_reviews', models.IntegerField(default=0, verbose_name='Новые отзывы')),
                ('with_xl_promotion', models.IntegerField(default=0, verbose_name='Объявлений с XL-продвижением')),
                ('favorites', models.IntegerField(default=0, verbose_name='Добавлено в избранное')),
                ('total_expenses', models.FloatField(default=0, verbose_name='Общие расходы')),
                ('promo_expenses', models.FloatField(default=0, verbose_name='Расходы на продвижение')),
                ('xl_expenses', models.FloatField(default=0, verbose_name='Расходы на XL и выделение')),
                ('discount_expenses', models.FloatField(default=0, verbose_name='Расходы на рассылку скидок')),
                ('service_level', models.FloatField(default=0, verbose_name='Уровень сервиса (%)')),
                ('balance_real', models.FloatField(default=0, verbose_name='Баланс кошелька')),
                ('balance_bonus', models.FloatField(default=0, verbose_name='Бонусный баланс')),
                ('advance', models.FloatField(default=0, verbose_name='CPA баланс')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='bot.avitoaccount', verbose_name='Аккаунт Авито')),
            ],
            options={
                'verbose_name': 'Дневной отчет',
                'verbose_name_plural': 'Дневные отчеты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отчета')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего объявлений')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('contacts', models.IntegerField(default=0, verbose_name='Контакты')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Конверсия в контакты (%)')),
                ('contact_cost', models.FloatField(default=0, verbose_name='Стоимость контакта')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Всего звонков')),
                ('answered_calls', models.IntegerField(default=0, verbose_name='Отвеченные звонки')),
                ('missed_calls', models.IntegerField(default=0, verbose_name='Пропущенные звонки')),
                ('total_chats', models.IntegerField(default=0, verbose_name='Всего чатов')),
                ('unanswered_chats', models.IntegerField(default=0, verbose_name='Неотвеченные чаты')),
                ('phones_received', models.IntegerField(default=0, verbose_name='Показы телефона')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Всего отзывов')),
                ('weekly_reviews', models.IntegerField(default=0, verbose_name='Новые отзывы за неделю')),
                ('with_xl_promotion', models.IntegerField(default=0, verbose_name='Объявлений с XL-продвижением')),
                ('favorites', models.IntegerField(default=0, verbose_name='Добавлено в избранное')),
                ('total_expenses', models.FloatField(default=0, verbose_name='Общие расходы')),
                ('promo_expenses', models.FloatField(default=0, verbose_name='Расходы на продвижение')),
                ('xl_expenses', models.FloatField(default=0, verbose_name='Расходы на XL и выделение')),
                ('discount_expenses', models.FloatField(default=0, verbose_name='Расходы на рассылку скидок')),
                ('service_level', models.FloatField(default=0, verbose_name='Уровень сервиса (%)')),
                ('balance_real', models.FloatField(default=0, verbose_name='Баланс кошелька')),
                ('balance_bonus', models.FloatField(default=0, verbose_name='Бонусный баланс')),
                ('advance', models.FloatField(default=0, verbose_name='CPA баланс')),
                ('avito_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='bot.avitoaccount', verbose_name='Аккаунт Авито')),
            ],
            options={
                'verbose_name': 'Недельный отчет',
                'verbose_name_plural': 'Недельные отчеты',
                'ordering': ['-date'],
            },
        ),
    ]
